### Unit - 3 ~ (4 marks)
- `pd.get_dummies`
- `np.where` (MIMP)

## IMPORT LIBRARIES AND DATASET

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

### PREPARE DATAFRAME

In [3]:
iris = load_iris()
df = pd.DataFrame(iris.data,columns=iris.feature_names)
print(df)
df['target'] = iris.target
df['species'] = df['target'].map({
    0:"setosa",
    1:"versicolor",
    2:"virginica"
})
df.head(1)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target species
0                5.1               3.5                1.4               0.2       0  setosa

## `pd.get_dummies`
- This method is used to convert categorical variables to boolean equivalents
- This conversion facilitates Machine learning analysis

In [4]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target species
0                5.1               3.5                1.4               0.2       0  setosa
1                4.9               3.0                1.4               0.2       0  setosa
2                4.7               3.2                1.3               0.2       0  setosa
3                4.6               3.1                1.5               0.2       0  setosa
4                5.0               3.6                1.4               0.2       0  setosa

In [6]:
pd.get_dummies(df, columns=["species"],drop_first=True)

     sepal length (cm)  sepal width (cm)  petal length (cm)  ...  target  species_versicolor  species_virginica
0                  5.1               3.5                1.4  ...       0               False              False
1                  4.9               3.0                1.4  ...       0               False              False
2                  4.7               3.2                1.3  ...       0               False              False
3                  4.6               3.1                1.5  ...       0               False              False
4                  5.0               3.6                1.4  ...       0               False              False
..                 ...               ...                ...  ...     ...                 ...                ...
145                6.7               3.0                5.2  ...       2               False               True
146                6.3               2.5                5.0  ...       2               False               True
147                6.5               3.0                5.2  ...       2               False               True
148                6.2               3.4                5.4  ...       2               False               True
149                5.9               3.0                5.1  ...       2               False               True

[150 rows x 7 columns]

## `np.where`
- This method is used to apply conditions to the given columns of a dataframe

In [7]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target species
0                5.1               3.5                1.4               0.2       0  setosa
1                4.9               3.0                1.4               0.2       0  setosa
2                4.7               3.2                1.3               0.2       0  setosa
3                4.6               3.1                1.5               0.2       0  setosa
4                5.0               3.6                1.4               0.2       0  setosa

In [8]:
df["size"] = np.where(df["sepal length (cm)"] > 6.5,"Large",
             np.where(df["sepal length (cm)"] > 5.5,"Medium",
             "Small"))

In [9]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target    species    size
0                  5.1               3.5                1.4               0.2       0     setosa   Small
1                  4.9               3.0                1.4               0.2       0     setosa   Small
2                  4.7               3.2                1.3               0.2       0     setosa   Small
3                  4.6               3.1                1.5               0.2       0     setosa   Small
4                  5.0               3.6                1.4               0.2       0     setosa   Small
..                 ...               ...                ...               ...     ...        ...     ...
145                6.7               3.0                5.2               2.3       2  virginica   Large
146                6.3               2.5                5.0               1.9       2  virginica  Medium
147                6.5               3.0                5.2               2.0       2  virginica  Medium
148                6.2               3.4                5.4               2.3       2  virginica  Medium
149                5.9               3.0                5.1               1.8       2  virginica  Medium

[150 rows x 7 columns]

## 190 
```
You've been given a dataset with apartment area and price information. There's a noticeable non-linear relationship between 
area and price. To address this you intend to categorize them into 'High', 'Medium', and 'Low' groups. Prices above $3,000,000 
are 'High', below $2,000,000 are 'Low', and between $2,000,000 and $3,000,000 are 'Medium'. Write a code to achieve this 
assuming that dataset has two columns named area and price.
```

In [ ]:
# Assuming that df Dataframe contains Price column 
df["Price_Group"] = np.where(df["Price"] > 3000000,"High",
             np.where(df["Price"] > 2000000,"Medium",
             "Low"))
print(df)

In [ ]:
191 3 In a survey dataset, you have a column representing participants' ages. You want to categorize ages into 'Young', 'Middle-aged', 
and 'Elderly' groups. Ages below 30 are 'Young', ages between 30 and 60 are 'Middle-aged', and ages above 60 are 'Elderly'. 
Write a code to achieve this assuming the dataset has a column named 'age'.

In [ ]:
192 3 In a customer dataset, you have a column representing customer incomes. You want to categorize incomes into 'Low', 'Medium', 
and 'High' groups. Incomes below 30000 are 'Low', incomes between 30000 and 70000 are 'Medium', and incomes above 70000 
are 'High'. Write a code to achieve this assuming the dataset has a column named 'income'.