## Unit-3 Feature Creation & Feature Transformation

## To Convert Categorical Columns to Numerical Columns

In [1]:
import pandas as pd

In [2]:
data = {
    'Marks':[40,42,42,41,43,45,44,49,45,42,46,48],
    'Gender':['Male','Female','Male','Female','Male','Female',
              'Male','Female','Male','Female','Male','Female']
}

df = pd.DataFrame(data)
df

    Marks  Gender
0      40    Male
1      42  Female
2      42    Male
3      41  Female
4      43    Male
5      45  Female
6      44    Male
7      49  Female
8      45    Male
9      42  Female
10     46    Male
11     48  Female

In [5]:
pd.get_dummies(df) #One-hot Encoding

    Marks  Gender_Female  Gender_Male
0      40          False         True
1      42           True        False
2      42          False         True
3      41           True        False
4      43          False         True
5      45           True        False
6      44          False         True
7      49           True        False
8      45          False         True
9      42           True        False
10     46          False         True
11     48           True        False

In [6]:
pd.get_dummies(df, drop_first = True) #One-hot Encoding

    Marks  Gender_Male
0      40         True
1      42        False
2      42         True
3      41        False
4      43         True
5      45        False
6      44         True
7      49        False
8      45         True
9      42        False
10     46         True
11     48        False

## Feature Creation

In [7]:
df

    Marks  Gender
0      40    Male
1      42  Female
2      42    Male
3      41  Female
4      43    Male
5      45  Female
6      44    Male
7      49  Female
8      45    Male
9      42  Female
10     46    Male
11     48  Female

In [8]:
import numpy as np
df['Result'] = np.where(df['Marks']>45,'Pass','Fail')

In [9]:
df

    Marks  Gender Result
0      40    Male   Fail
1      42  Female   Fail
2      42    Male   Fail
3      41  Female   Fail
4      43    Male   Fail
5      45  Female   Fail
6      44    Male   Fail
7      49  Female   Pass
8      45    Male   Fail
9      42  Female   Fail
10     46    Male   Pass
11     48  Female   Pass

In [12]:

df['Grade'] = np.where(df['Marks'] > 47, 'A',        # if
               np.where(df['Marks'] > 45, 'B',       # elif
               np.where(df['Marks'] > 43, 'C', 'D'))) # else

print(df)

    Marks  Gender Result Grade
0      40    Male   Fail     D
1      42  Female   Fail     D
2      42    Male   Fail     D
3      41  Female   Fail     D
4      43    Male   Fail     D
5      45  Female   Fail     C
6      44    Male   Fail     C
7      49  Female   Pass     A
8      45    Male   Fail     C
9      42  Female   Fail     D
10     46    Male   Pass     B
11     48  Female   Pass     A

## Arithmatic Operations

In [15]:
data = {
    'A':[10,20,15,12],
    'B':[40,42,44,45]
}

df = pd.DataFrame(data)
df['A']+2

0    12
1    22
2    17
3    14
Name: A, dtype: int64

In [16]:
df['A'] + df['B']

0    50
1    62
2    59
3    57
dtype: int64

In [19]:
df['A'] / df['B']

0    0.250000
1    0.476190
2    0.340909
3    0.266667
dtype: float64

# Train-Validation Split

- using Scikit-learn

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
data = {
    'Marks':[40,42,42,41,43,45,44,49,45,42,46,48],
    'Gender':['Male','Female','Male','Female','Male','Female',
              'Male','Female','Male','Female','Male','Female']
}

df = pd.DataFrame(data)
x = df["Gender"]
y = df['Marks']

In [68]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.2, random_state  = 10 ) # rs limit (0-10)
x_train

5     Female
11    Female
8       Male
10      Male
3     Female
1     Female
0       Male
4       Male
9     Female
Name: Gender, dtype: object

In [66]:
x_train

10      Male
2       Male
11    Female
4       Male
5     Female
7     Female
1     Female
0       Male
9     Female
Name: Gender, dtype: object

## cross_validation skip due to prediciton

# continue into next phase .......